dfinity/cycles-ledger

- cycles-ledger/src/storage.rs
- cycles-ledger/tests/tests.rs
- fake-cmc/src/main.rs
Bug: If canister settings are `Some` but the controllers therein are `None` then the cycles ledger ends up as the sole controller of the new canister instead of the user/caller.
> fix: set correct controller if no controller is specified in canister settings

- Cargo.lock
- cycles-ledger/Cargo.toml
- cycles-ledger/cycles-ledger.did
- cycles-ledger/src/config.rs
- cycles-ledger/src/endpoints.rs
- cycles-ledger/src/main.rs
- cycles-ledger/src/storage.rs
- cycles-ledger/tests/tests.rs
Completes [SDK-1334](https://dfinity.atlassian.net/browse/SDK-1334)
If a duplicate `create_canister` request gets answered, the canister id should be returned alongside the block number because there is no other way to figure out the canister id.
[SDK-1334]: https://dfinity.atlassian.net/browse/SDK-1334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: return canister id for duplicate create_canister calls

- .github/workflows/ci.yml
- fake-cmc/src/main.rs
Updating IC version to newer release. There was a change of an error message in case of duplicate canister, which needs to be updated in order for tests to work
> Update to newer IC version

- .github/workflows/release-with-github.yml
Workflow fails with `the 'uses' attribute must be a path, a Docker image, or owner/repo@ref`
> chore: fix release-with-github workflow

- .github/workflows/release.yml
release fails with `.dfx/local/canisters/fake-cmc/fake-cmc.did: no such file or directory`
> fix: release workflow targets nonexistent file

- Cargo.lock
- cycles-ledger/Cargo.toml
- cycles-ledger/src/storage.rs
Removing scopeguards for panics. They are not needed, since the relevant functions won't panic in practice. The only situations where these functions can panic is if there is a failure in encoding call arguments. Such problem would be caught by tests.
> Fix: Remove scopeguards

- Cargo.lock
- cycles-ledger/Cargo.toml
- cycles-ledger/src/storage.rs
- cycles-ledger/tests/tests.rs
Unifying the code to use ciborium everywhere, so that we can remove serde_cbor from dependencies
> Chore: Remove serde cbor

- cycles-ledger/tests/tests.rs
Adding tests to verify that all relevant endpoints fail if memo is invalid (size larger that max allowed)
> Chore: Tests for invalid memo

- dfx.json
This PR simply adds the required pullable metadata.
To verify the overall workflow, we will need to make a new release so that the wasm module in GitHub release artifacts will have these metadata. And that release should not be "pre-release" in order to be accessible  using "latest" label.
And there is an issue on the `dfx` side which requires `wasm_hash_url` to contains the hash only. Instead of modifying the CI of this project, I change the `dfx deps pull` to accept `shasum` output. [PR](https://github.com/dfinity/sdk/pull/3563) is pending.
I removed the "pre-release" label of the 0.2.8 release. So that I could verify the `wasm_url` and `wasm_hash_url` can be reached.
And I also verified the content of `init_guide` field is correct to deploy the canister locally.
> feat: pullable

- dfx.json
`max_transactions_per_request` was renamed to `max_blocks_per_request`
`dfx` will (starting from v0.17.0) allow providers to set `init_arg` in pullable metadata.
> fix: pullable init_guide and add init_arg

- cycles-ledger/cycles-ledger.did
- cycles-ledger/tests/gen.rs
- cycles-ledger/tests/tests.rs
This PR adds a state machine library for the cycles-ledger as well as a test to check that upgrading the ledger preserves the state. The test uses the state machine library. Specifically, this PR adds:
1. A `gen.rs` file that contains `arb_cycles_ledger_call_state` which is a `proptest` generator of valid cycles-ledger calls.
2. `CyclesLedgerCall` which models a call to the cycles-ledger. A call is represented as the caller plus the arguments.
3. The `CyclesLedgerApplyCall` trait which abstract over "cycles ledgers" and allow to apply a `CyclesLedgerCall` to them.
4. Two implementation of `CyclesLedgerApplyCall`: 1) `CyclesLedgerInStateMachine` which models the cycles-ledger deployed in a `StateMachineTest` environment and 2) `CyclesLedgerInMemory` which models the cycles-ledger purely in …
> feat: add test that checks that upgrading the ledger preserves the state

- Cargo.lock
- cycles-ledger/Cargo.toml
- cycles-ledger/tests/tests.rs
The current `test_icrc1_test_suite` implementation uses `FutureExt`'s [`now_or_never`](https://docs.rs/futures-util/latest/futures_util/future/trait.FutureExt.html#method.now_or_never) to deal with async code. The issue with that is that in case of timeout you get an `unwrap` error instead of a timeout. This PR changes that by making the test async and using `tokio::test` macro.
> chore: switch to `tokio::test` for the `test_icrc1_test_suite`

- cycles-ledger/tests/client.rs
- cycles-ledger/tests/tests.rs
1. change the `deposit` client function to take in input the `memo`
2. check the `memo` in the `test_deposit_flow`
3. add a tiny util to create ICRC-1 Accounts
> chore: check block created by depositor

- cycles-ledger/tests/client.rs
- cycles-ledger/tests/gen.rs
- cycles-ledger/tests/tests.rs
1. remove useless parts of the tests.
2. proper naming for client functions, e.g. `icrc3_get_blocks` instead `get_raw_blocks`. In general, each function has been changed to use the name of the canister method that it is calling.
3. Add `TestEnv` to replace test setup (created `StateMachine`->install ledger->install depositor) with a single function and to avoid passing `env` and the canister id to every client function. E.g. `icrc1_total_supply(env, ledger_id)` is now `env.icrc1_total_supply()`.
5. Standardize how arguments are passed to functions. Most functions now take in input the `Principal` caller and a single argument which is the payload to serialize and pass in the call. Note that for egonomics reasons some functions, such as `deposit` and `icrc3_get_blocks`, take in input a …
> chore: tests cleanup and ergonomics

- cycles-ledger/src/endpoints.rs
- cycles-ledger/src/storage.rs
- cycles-ledger/tests/tests.rs
1. add the ability to convert blocks to readable strings for better test errors readability
2. add a couple of utilities to do `assert_eq` using `Display` instead of `Debug` for better test errors readability (e.g. account now is printed with the textual format in ICRC-1 instead of two arrays of bytes)
3. add checks for blocks for deposit and withdraw operation
> chore: check blocks for deposit and withdraw in tests

- cycles-ledger/src/storage.rs
- cycles-ledger/tests/client.rs
- cycles-ledger/tests/tests.rs
1. change `withdraw` and `create_canister` such that the user pays a fee in case of reimburse/penalized block is created
2. fix a bug in `assert_vec_display_eq`
> feat: reimburse fee

- cycles-ledger/src/storage.rs
Remove `log_error_and_trap` because logging before trapping does nothing as the state of the canister is reverted back to before the endpoint was called.
> chore: remove log_error_and_trap

- cycles-ledger/src/storage.rs
- cycles-ledger/tests/tests.rs
1. test most permutations of arguments
2. more tests for error cases such as too old an created in the future
3. consolidate some of the existing tests, e.g. `test_basic_transfer`
> chore: add more tests for `icrc1_transfer`

- cycles-ledger/cycles-ledger.did
- cycles-ledger/src/endpoints.rs
- cycles-ledger/src/lib.rs
- cycles-ledger/src/main.rs
- cycles-ledger/src/storage.rs
- cycles-ledger/tests/client.rs
- cycles-ledger/tests/tests.rs
Adds `withdraw_from` to the cycles ledger, also makes it so that reimbursing a block from a failed `withdraw` attempt costs 1x `FEE` because a block is produced. `create_canister` will receive the same treatment when I implement `create_canister_from`
> feat: withdraw_from

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
Bump `ic-cdk` to the latest patch version to fix a memory leak
> chore: bump ic-cdk patch version

- CHANGELOG.md
- Cargo.lock
- cycles-ledger/Cargo.toml
- cycles-ledger/src/storage.rs
- cycles-ledger/tests/tests.rs
The [ICRC-3 standard](https://github.com/dfinity/ICRC-1/tree/main/standards/ICRC-3#blocks-verification) specifies that the `last_block_index` value in the certificate returned from the `icrc3_get_tip_certificate` endpoint shall be encoded using [leb128](https://en.wikipedia.org/wiki/LEB128#Unsigned_LEB128). The value has until now been encoded as a Big Endian-encoded `u64`, but this PR proposes to change that to a `leb128` encoding as per the ICRC-3 standard.
> fix: FI-1574: last_block_index shall be leb128 encoded

- INTERFACE_SPECIFICATION.md
- README.md
In an effort to have clear and consistent documentation of the API of system canisters, this PR adds a dedicated `INTERFACE_SPECIFICATION.md` file.
> chore: Adding the interface specification

- .github/workflows/ci.yml
- CHANGELOG.md
- Dockerfile
- cycles-ledger/src/lib.rs
- cycles-ledger/src/storage.rs
- cycles-ledger/tests/tests.rs
- dfx.json
- rust-toolchain.toml
Fixes [FI-1690](https://dfinity.atlassian.net/browse/FI-1690)
Update `now` after an `await` so we don't have decreasing timestamps in the chain of blocks.
This cannot be tested in unit tests because the state machine binary in use does not advance time automatically. Updating the state machine binary is not possible at the moment
Also bumped a bunch of tooling: dfx, GH actions, Rust. Otherwise CI and/or rust-analyzer are unhappy
[FI-1690]: https://dfinity.atlassian.net/browse/FI-1690?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: blocks can have decreasing timestamps

- README.md
Fix the documentation for `deposit`, since a transfer fee is in fact charged.
> docs: Fix the deposit docs in the README

- CHANGELOG.md
- cycles-ledger/cycles-ledger.did
- cycles-ledger/src/config.rs
- cycles-ledger/src/main.rs
- cycles-ledger/tests/tests.rs
Add support for `initial_balances` in `InitArgs`. When specifying initial balances it is up to the installer to ensure that the cycles ledger has sufficient cycles available to spend these cycles.
https://dfinity.atlassian.net/browse/SDK-2280
> feat: specify initial balances
